### PR TITLE
feat(util/pingpong): add user/pingpong.c

### PR DESCRIPTION
**Pull request by LittleYe233**
Add user/pingpong.c for the "pingpong" experiment.

### CODE REVIEW

**Comment by inclyc** [comment]
> [Merge branch 'util' into dev_util_pingpong](https://github.com/inclyc/Sophia-xv6-labs-2021/pull/3/commits/650debac4edc4e6829da0d33ed79d8b5609cfd0b)

Traditionally we do not *merge* any commit from remote, instead, you should use `git pull --rebase` to make your history clearer.

**Comment by inclyc** [comment]
Branch names usually separated by `-`, not underline `_` and the hierarchical layouts are represented just like directories.

If I were you, I will create branches like:

```
dev-util/pingpong
dev-util/sleep
```

etc.

**Review by inclyc — APPROVED** [review]
LGTM with some little git nits.

**Comment by LittleYe233** [comment]
> Branch names are usually separated by `-`, not underline `_` and the hierarchical layouts are represented just like directories.
> 
> If I were you, I will create branches like:
> 
> ```
> dev-util/pingpong
> dev-util/sleep
> ```
> 
> etc.

Ah... I had pushed some of my first commits to branches named like `dev/util/xxx` before, but these commits did not meet the coding guideline and got rejected. Before moving all the source files into a new branch, I tried to manage the new commits in such like `dev/xxx`, but the branch was conflict with the old `dev/util/xxx`, so I finally chose the names like `dev_util_xxx`. At that time I did forget to use something like `dev-util/xxx`. So weird.

In fact I do seldom see branches named with underscores, but I have not considered it as a guideline or a convention...

**Comment by LittleYe233** [comment]
Oh, it seems that GitHub has not pushed this comment via E-mail, so I did not know it for a long time... Very sorry for that!

> Traditionally we do not *merge* any commit from remote

I did not find the manual CLI instructions on how to resolve such conflicts (those on how to merge a PR really exist, however). After I clicked the "Mark as resolved" button in the web editor, this commit was automatically pushed to the remote server quickly - as you see it merged the default branch into `dev_util_pingpong`...

> This "Merge" commit is fairly ugly in my opinion.

Actually "Merge" commits along with messy commit networks are annoying for me sometimes, and I think these merges that pull the remote branch to local and then push back are especially "ugly". But I am *still* not familiar with "rebase". I seldom use it, maybe for some "dark memories" (such as an unavoidable `git rebase` after messing up the commit history), thus I am always afraid of what might happens after a rebase, even potentially fatal damage to the whole repo.

But at present it may be necessary to rebase after fetching. So I decide to have a try.

**Pull request merged**
