### PR TITLE
Experiment "Backtrace" of lab traps

### PR DESCRIPTION
**Pull request by LittleYe233**
Formats some original source files via clang-format.

Completes all related source code.

Finishes the whole experiment.

This PR is based on #14 which is awaiting reviews.

### CODE REVIEW

**Review by inclyc — COMMENTED** [review]
> build: remove all -Werror and -Wno-error from Makefile

Did you removed "-Wno-error"? I can't see such changes.

**Comment by inclyc** [comment]
你的所有commit描述都过于抽象，应该写一点点具体的东西。比如，用什么方法，完成了什么实验

"complete" 是一个毫无意义的抽象词汇。

**Comment by LittleYe233** [comment]
> Did you removed "-Wno-error"? I can't see such changes.

"-Wno-error" came from PR #1. In the first attempt I replaced "-Werror" with "-Wno-error", then directly removed it. The commit was cherry-picked from that PR and its message did not change.

> 你的所有commit描述都过于抽象，应该写一点点具体的东西。比如，用什么方法，完成了什么实验

Alright. Sometimes, I am not sure what I need to write down in commit messages and what I do not need to. I am afraid that there is too much useless information in them. I will have a try to add more details in commit messages.

**Comment by inclyc** [comment]
> cherry-picked from that PR and its message did not change.

或许应该用 `git commit --amend` 说明一下。

**Pull request merged**
